### ISSUE TITLE
Support to RGBA

### ISSUE THREAD

**Issue by AndreaStevanato** [onmyway133/XcodeColorSense2#1]
Add support to RGB with alpha channel, for example: `UIColor(hexRgba: "7FA311FF")`

**Comment by onmyway133** [comment]
@AndreaStevanato Interesting, I myself never use hex with alpha info. Mind making a PR for this? That would be great

**Comment by Lutzifer** [comment]
+1

**Comment by onmyway133** [comment]
@Lutzifer Hi, actually the hard work of processing colors is handled by https://github.com/onmyway133/Farge, you can make a PR to your liking, and I'm happy to review it ❤️
